name: Release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Import GPG key
        run: |
          echo "${{ secrets.OSSH_GPG_SECRET_KEY }}" | gpg --import --batch --yes --passphrase "${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}"
      - name: print GPG version and the location of the keyring
        run: |
          gpg --version
          gpg --list-secret-keys
          ls -la ~/.gnupg/
      - name: Publish package
        run: ./gradlew  --stacktrace publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_secretKey: ${{ secrets.OSSH_GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_secretKeyPassword: ${{ secrets.OSSH_GPG_SECRET_KEY_PASSWORD }}
